version: '2'
services:
  ruby:
    image: ruby:2.4
    command: bash
    working_dir: /app
    environment:
      BUNDLE_PATH: /app/vendor/bundle
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - .:/app:cached
      - ~/.gitconfig:/root/.gitconfig
